### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by geoffreysflaminglasersword**

### CODE REVIEW

**Comment by geoffreysflaminglasersword** [comment]
continued from #14 

> I see! and I gotta say, those look awesome. Great improvement upon my original, rather simple design 😅
> 
> For the sake of simplicity I would keep the plugin exclusion to the plugin name. Most people don't know stuff like plugin IDs, and I don't even have an idea what the usecase for a regex could be here.
> 
> Also, I'd suggest hardcoding that divide and conquer excludes itself.
> 
> The unbisect, rebisect commands etc are awesome, but I am pretty sure they need some explanations in the readme for the less-tech-savvy users. Also, the current commands that I originally created can probably be removed by now, since your commands are smarter anyway?


- Exclusion is only by name by default. I figure the id's don't change as often as the names, and that if eventually other plugins use this plugin's functionality they'll probably want to pass id's. I don't see the harm in having the option there but disabled by default
- DAC should already be ignored by default? Is it not on your end?
- Yeah, I'll update the readme and add a gif or two
- Yeah, so I wasn't quite finished refactoring, that's why I was leaving #14 open. It's all removed now that it works with snippets.

**Comment by geoffreysflaminglasersword** [comment]
i.e. don't worry about merging this, I'm leaving the request open so all of the changes can be merged in one pr to make things simpler on master

**Comment by geoffreysflaminglasersword** [comment]
> * Exclusion is only by name by default. I figure the id's don't change as often as the names, and that if eventually other plugins use this plugin's functionality they'll probably want to pass id's. I don't see the harm in having the option there but disabled by default

Also, I guess my original thought for allowing regex is stuff like this:
image
If you have a bunch of similarly named items, or you want to make sure you don't disable any plugins that are command-palette-related (or hotkey related, etc.) then you can easily exclude them all

**Comment by chrisgrieser** [comment]
> DAC should already be ignored by default? Is it not on your end?

it is, but I don't see why the user should be able to even remove DAC from the list of ignored plugins. Doing so will definitely break any sort of bisecting being done, and I cannot think of a scenario where it would make sense to let DAC disable itself.

> If you have a bunch of similarly named items, or you want to make sure you don't disable any plugins that are command-palette-related (or hotkey related, etc.) then you can easily exclude them all

Oh I see. Yeah, excluding only hotkey plugins is a scenario that would make sense to me, yeah.

**Comment by geoffreysflaminglasersword** [comment]
> it is, but I don't see why the user should be able to even remove DAC from the list of ignored plugins. Doing so will definitely break any sort of bisecting being done, and I cannot think of a scenario where it would make sense to let DAC disable itself.

- It won't break anything, the last reset would just get restored when it's reenabled. There's *probably* not a good reason for letting them do it, but it makes the code simpler and demonstrates to the user how to use the feature. I don't care too much either way but I've spent all the time I can on this for now

Anyways, I think it's in a good state for a 1.0 release

**Pull request merged**
