### PR TITLE
Added plugin filtering and improved bisection commands

### PR DESCRIPTION
**Pull request by geoffreysflaminglasersword**
See https://github.com/chrisgrieser/obsidian-divide-and-conquer/issues/2#issue-1127978685

### CODE REVIEW

**Comment by geoffreysflaminglasersword** [comment]
@chrisgrieser Would appreciate if you could merge this, it looks like you've made some changes to master

**Comment by chrisgrieser** [comment]
Fantastic, thanks! unluckily, you did your work at the same time that @valentine195 (aka javalent) contributed commands for CSS snippet bisecting CSS snippets. I could resolve the conflicts, so I did merge it, but the css snippets bisecting still works according to the "old" logic while the bisection of plugins works with your new code base.

So either me, javalent, or you should look into translating the css snippet bisection into the new logic before I am doing releasing the improvements – when css snippets and plugins are bisected differently, I fear that it would confuse users quite a lot.

**Comment by geoffreysflaminglasersword** [comment]
> Fantastic, thanks! Your changes really improve a lot.
> 
> Unluckily, you did your work at the same time that @valentine195 (aka javalent) contributed commands for CSS snippet bisecting CSS snippets. I could resolve the conflicts, so I did merge it, but the css snippets bisecting still works according to the "old" logic while the bisection of plugins works with your new code base.
> 
> So either me, javalent, or you should look into translating the css snippet bisection into the new logic before I am doing releasing the improvements – when css snippets and plugins are bisected differently, I fear that it would confuse users quite a lot.

I can't say when I'll have the time, but if no one has gotten to it by the time I do then I will check it out

**Comment by chrisgrieser** [comment]
@geoffreysflaminglasersword Would you be interested in taking over maintainership of Divide and Conquer? 

I frankly have a bit too many plugins to maintain, and your PR is an essentially a full rewrite of the plugin anyway. It's been unreleased for a few months now since I didn't have the time to look into it, but I was thinking, when the code of this plugin is mostly yours now, it probably makes more sense if you were the maintainer?

**Comment by geoffreysflaminglasersword** [comment]
> @geoffreysflaminglasersword Would you be interested in taking over maintainership of Divide and Conquer?
> 
> I frankly have a bit too many plugins to maintain, and your PR is an essentially a full rewrite of the plugin anyway. It's been unreleased for a few months now since I didn't have the time to look into it, but I was thinking, when the code of this plugin is mostly yours now, it probably makes more sense if you were the maintainer?

Oh, I suppose so. Given how long it took me to see this I may not be the best choice. But I can spend some time on this tomorrow and get it into a good state

**Comment by chrisgrieser** [comment]
> Given how long it took me to see this I may not be the best choice.

yeah well, considering I basically have zero time to maintain this repo on top of all my others, it's still an improvement 🙈

I added you as maintainer

**Pull request merged**
