### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by geoffreysflaminglasersword**
@chrisgrieser I've added some UI buttons and colorization to the community plugins tab. I'll have to do some cleanup and make everything work with snippets but if you could just try out the functionality and let me know of any bugs you find it'd help

### CODE REVIEW

**Comment by geoffreysflaminglasersword** [comment]
image

**Comment by chrisgrieser** [comment]
tbh, since I am barely familiar with the new code base, it feels a bit pointless to be code reviewer for this 😅 

since you now have collaborator access, feel free to commit to the repo directly and make releases from now on. 🙂

**Comment by geoffreysflaminglasersword** [comment]
> tbh, since I am barely familiar with the new code base, it feels a bit pointless to be code reviewer for this 😅 
> 
> since you now have collaborator access, feel free to commit to the repo directly and make releases from now on. (And add yourself to the README, of course 🙂 )

Oh, I don't mean to review the code, just try out the functionality

**Comment by chrisgrieser** [comment]
I see! and I gotta say, those look awesome. Great improvement upon my original, rather simple design 😅 

For the sake of simplicity I would  keep the plugin exclusion to the plugin name. Most people don't know stuff like plugin IDs, and I don't even have an idea what the usecase for a regex could be here.

Also, I'd suggest hardcoding that divide and conquer excludes itself.

The unbisect, rebisect commands etc are awesome, but I am pretty sure they need some explanations in the readme for the less-tech-savvy users. Also, the current commands that I originally created can probably be removed by now, since your commands are smarter anyway?

**Comment by geoffreysflaminglasersword** [comment]
continuing on #15

**Pull request merged**
